name: gixstapose
channels:
  - conda-forge
dependencies:
  - fresnel=0.13
  - gsd
  - matplotlib
  - mbuild
  - numpy
  - openbabel
  - pillow
  - pip
  - pyside2
  - python
  - pip:
    - git+https://bitbucket.org/cmelab/cme_utils
