name: gixstapose
channels:
  - conda-forge
dependencies:
  - fresnel=0.13.1
  - gsd=2.4.1
  - ipython=7.10.0
  - jupyter
  - matplotlib=3.3.4
  - mbuild=0.10.13
  - nodejs>=10
  - numpy=1.20.1
  - openbabel=3.1.1
  - pillow=8.1.2
  - pip=21.0.1
  - py3Dmol=0.8.0
  - pyside2=5.13.2
  - pytest
  - pytest-cov
  - python=3.7
  - rowan=1.3.0
  - pip:
    - git+https://bitbucket.org/cmelab/cme_utils
    - git+https://github.com/cmelab/gixstapose@v0.0.1
