name: gixstapose-ex
channels:
  - conda-forge
dependencies:
  - fresnel=0.13.1
  - gsd=2.4.1
  - jupyterlab=3.0.10
  - ipython=7.10.0
  - matplotlib=3.3.4
  - mbuild=0.10.13
  - nodejs>=10
  - numpy=1.20.1
  - openbabel=3.1.1
  - pillow=8.1
  - pip=21.0.1
  - py3Dmol=0.8.0
  - pyside2=5.13.2
  - python=3.8.8
  - rowan=1.3.0
  - pip:
    - git+https://bitbucket.org/cmelab/cme_utils
