name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup miniconda
      uses: goanpeca/setup-miniconda@v1.6.0
      with:
        # https://github.com/goanpeca/setup-miniconda
        activate-environment: cmelab
        environment-file: environment.yml
        auto-activate-base: false
    
    - name: check env
      shell: bash -l {0}
      run: |
          conda info
          conda list
          which python
        
    - name: run pytest
      shell: bash -l {0}
      run: |
          python -m pip install pytest
          python -m pytest

